- name: install mysql server
  ansible.builtin.package:
    name: mysql-server
    state:  present

- name: start and enable mysql
  ansible.builtin.service:
    nam:  mysqld
    state:  started
    enabled:  yes

    